version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: fit-db
      POSTGRES_USER: db-user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - default-network

  api:
    depends_on:
      - db
    image: x03xd/fit-app-api:latest 
    ports:
      - "8000:8000"
    environment:
      DATABASE_NAME: fit-db
      DATABASE_USER: db-user
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      SENTRY_DSN: "https://f4c55855e818f45192bda6745488bd33@o4508155328069632.ingest.de.sentry.io/4508155330166864"
      UI_URL: http://localhost:3000
    networks:
      - default-network
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "

  ui:
    image: x03xd/fit-app-ui:latest 
    ports:
      - "3000:3000"
    environment:
      SENTRY_DSN: https://698ab724771677ea82304be81d9e0f13@o4508155328069632.ingest.de.sentry.io/4508155394523216
      REACT_APP_API_URL: http://localhost:8000/api
    networks:
      - default-network

networks:
  default-network:
    driver: bridge 

volumes:
  db_data:
